export type ErrorCode = 
    "PARSE_RESPONSE_FAILED" |
    "SERVER_ALREADY_UP" |
    "CHANNEL_NOT_FOUND" |
    "CHANNEL_NOT_VC" | 
    "JOIN_VC_FAILED" |
    "AUDIOGUILD_NOT_FOUND" |
    "AUDIOGUILD_ALREADY_INITIALIZED"